application: geolocationsample 
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: main.py
